### ISSUE TITLE
Different cache settings?

### ISSUE THREAD

**Issue by max-sixty** [actions-rust-lang/setup-rust-toolchain#16]
We use some more specific cache settings than this action offers. I tried disabling the cache from this action, and adding another step, but:
- If I put this action first, the cache doesn't seem to get hit https://github.com/PRQL/prql/pull/2558/files#diff-b73931d39044edca7c78f83713af7326a8d63dac151088b8d905e39f060ed8a6R29-R37 (maybe it's a deterministic change such that it would get hit in future though?)
- If I put the cache first, the cache is hit but isn't used

**Comment by jonasbb** [comment]
Your workflow looks good to me.
This actions sets some environment variables which can affect the cache keys used by Swatinem/rust-cache and can make cargo incapable of using old caches (e.g., incremental is turned off). That should settle itself after you create a new cache with the new data and key. You only enable cache storage on main `save-if: ${{ github.ref == 'refs/heads/main' }}` so you wouldn't see that yet.

I'm confident everything will work out if you merge the code. You can test everything in a fork to make sure the cache storing on the main branch works.

**Comment by max-sixty** [comment]
Thanks — that makes sense, I'll close!
