### ISSUE TITLE
Consider backporting curl bugfix from upstream

### ISSUE THREAD

**Issue by HadrienG2** [actions-rust-lang/setup-rust-toolchain#22]
See https://github.com/dtolnay/rust-toolchain/pull/94 for context.

**Comment by HadrienG2** [comment]
But see also https://github.com/dtolnay/rust-toolchain/issues/95 for a possible caveat.

**Comment by jonasbb** [comment]
I have seen those commits but they do not seem like a clear win. Maybe these tweaks could be mentioned in the readme for those running into the problem more often.

**Comment by jonasbb** [comment]
This doesn't seem necessary to implement anymore.
