### ISSUE TITLE
toolchain file not properly overriden

### ISSUE THREAD

**Issue by fprasx** [actions-rust-lang/setup-rust-toolchain#31]
Related: #26 #28 

It seems like the fix from #30 does not properly override the toolchain specified by `rust-toolchain.toml`. Using `rustup override set $TOOLCHAIN` instead of `rustup default $TOOLCHAIN` seems to do the trick:
![Screenshot 2024-01-12 at 12 25 08 PM](https://github.com/actions-rust-lang/setup-rust-toolchain/assets/91577249/f23c4479-e138-4fe6-8a70-194710535a66)

I can make a PR if this seems like a desirable fix.

**Comment by robjtede** [comment]
Good catch! Seems reasonable, I'd approve a PR for this suggested fix 👍🏻

**Comment by fprasx** [comment]
Sounds good: see #33.
