### ISSUE TITLE
The cache is not functioning effectively

### ISSUE THREAD

**Issue by NPCDW** [actions-rust-lang/setup-rust-toolchain#36]
Could you please help me look at this issue, as I am unsure whether there is an issue with my method of use?
[https://github.com/Swatinem/rust-cache/issues/184](https://github.com/Swatinem/rust-cache/issues/184)

**Comment by jonasbb** [comment]
I think this is working as designed: https://github.com/Swatinem/rust-cache/issues/74 and https://github.com/actions/cache/blob/main/tips-and-workarounds.md#use-cache-across-feature-branches

Can you re-run all actions for a tag and see if you get a cache hit then? I expect that then you will get a cache hit.

**Comment by NPCDW** [comment]
Thank you for your answer, I understand now.
