### ISSUE TITLE
Add option to persist specific directories for caching

### ISSUE THREAD

**Issue by pranc1ngpegasus** [actions-rust-lang/setup-rust-toolchain#43]
The sqlx crate places SQL query cache files in the `.sqlx` directory.
To reduce CI execution time, it would be effective to cache this .sqlx directory.
I would like to request the ability to cache arbitrary directories using an option similar to the cache-directories option in Swatinem/rust-cache.

**Comment by jonasbb** [comment]
Implemented with #44
